### ISSUE TITLE
Show desktop website

### ISSUE THREAD

**Issue by Ronnyrr** [silverstripe/silverstripe-mobile#44]
I want to make a button so that user can view the desktop website. Is this possible? Thanks :)

**Comment by helenclarko** [comment]
Hi Ronnyrr,

Use the following:

On Mobile Site to go to Full Site:
<a href="http://website.com/$URLSegment?fullSite=1">Full site</a>

On Full Site to go to Mobile:
<a href="http://m.website.com/$URLSegment?fullSite=0">Mobile site</a>

-helenclarko

**Comment by bueckl** [comment]
Muchas gracias por su mensaje.

Estoy actualmente de vacaciones y sin acceso a mi correo electrónico. Responderé su email a partir del día 3 de Septiembre.

Si necesita asistencia inmediata, puede llamarme al +34 603 61 54 70.

Muchas gracias por su comprensión!

Jochen Gülden

*********************************************

Dear clients & friends

Thank you for your email. I’m I'm currently on vacation and will be back at 4th of September 2015. During this period I will have limited access to my email.

If you need immediate assistance before then, you may reach me at my mobile (+34 603 61 54 70)

Best Regards,

Jochen Gülden

**Comment by dhensby** [comment]
These kinds of questions should be in the forum.
